# Generated by Django 2.2.3 on 2019-07-18 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=50)),
                ('r_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_rate', models.IntegerField(default=0)),
                ('r_desc', models.CharField(max_length=200, null=True)),
                ('r_date', models.DateField(default=datetime.date.today)),
                ('r_like', models.IntegerField(default=0)),
                ('r_reply', models.IntegerField(null=True)),
                ('r_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant')),
                ('r_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_comment_id', models.IntegerField(null=True)),
                ('c_desc', models.CharField(max_length=200, null=True)),
                ('c_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Review')),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.User')),
            ],
        ),
    ]
