# Generated by Django 2.2.3 on 2019-07-14 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='c_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
