# Generated by Django 2.2.3 on 2019-07-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='c_comment_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='c_reply_user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
