# Generated by Django 2.2.3 on 2019-07-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_comment_c_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='c_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='c_reply',
            field=models.IntegerField(null=True),
        ),
    ]
